import numpy as np

print( f"list( range(5, 10) ) = { list( range(5, 10) ) }" )
print( f"list( range(15, 20) ) = { list( range(15, 20) ) }" )
print( f"list( range(0, 5) ) = { list( range(0, 5) ) }" )
print( f"list( range(20, 25) ) = { list( range(20, 25) ) }" )

l = [ list( range(5, 10) )
    , list( range(15, 20) )
    , list( range(0, 5) )
    , list( range(20, 25) ) ]

print( f"List l = { l }" )

arr = np.array( l )
print()
print( "Numpy array arr," )
print( arr )
print()
print( "Accessing Single Element\n" )
print( f"arr[ 2, 3 ] = { arr[ 2, 3 ] }\n" )
print( f"arr[ 1, 1 ] = { arr[ 1, 1 ] }\n" )

#Syntax :- arr[ row_start : row_end, col_start : col_end ]
print( "All Rows and ALL Columns," )
print( arr[ : , : ] )
print()
print( " Only Row_start and ALL Columns," )
print( arr[ 2 : , : ] )
print()
print( " Only Row_end and ALL Columns," )
print( arr[  : 2 , : ] )
print()
print( " Rows_start : Row_end and ALL Columns," )
print( arr[ 1 : 3 , : ] )
print()
print( " ALL ROWS and ALL Columns," )
print( arr[ : ,  : ] )
print()
print( " ALL ROWS and Column_start," )
print( arr[ : , 2 : ] )
print()
print( " ALL ROWS and Column_end," )
print( arr[ : ,  : 2 ] )
print()
print( " ALL ROWS and Column_start : Column_end," )
print( arr[ : , 2 : 4 ] )
print()
print( " Only Row_start and Column_start : Column_end," )
print( arr[ 2 : , 2 : 4 ] )
print()
print( "Row_start : Row_end and Column_start : Column_end," )
print( arr[ 1 : 3 , 2 : 4 ] )
print(  )
print( arr )